[package]
name = "pact-protobuf-plugin"
version = "0.1.11"
edition = "2021"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>"]
description = "Pact plugin for Protobufs and gRPC"
homepage = "http://www.pactflow.io"
repository = "https://github.com/pactflow/pact-protobuf-plugin"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
tonic = "0.8.0"
prost = "0.11.0"
prost-types = "0.11.1"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.1.2", features = ["v4"] }
maplit = "1.0.2"
pact_matching = "0.12.8"
pact_models = "0.4.2"
pact_verifier = "0.13.7"
pact-plugin-driver = "0.1.8"
anyhow = "1.0.42"
futures = "0.3"
async-trait = "0.1.51"
os_info = "3.0.7"
zip = "0.6.2"
serde_json = "1.0.71"
serde_yaml = "0.9.9"
tempfile = "3.2.0"
itertools = "0.10.1"
md5 = "0.7.0"
base64 = "0.13.0"
bytes = "1.1.0"
clap = { version = "3.2.17", features = ["cargo", "env"] }
hyper = { version = "0.14", features = [ "full" ] }
http = "0.2.6"
tower = { version = "0.4", features = [ "full" ] }
tower-service = { version = "0.3" }
tower-http = { version = "0.3.4", features = [ "full" ] }
http-body = "0.4"
tracing = "0.1.34"
tracing-core = "0.1.26"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "local-time", "tracing-log"] }
tracing-appender = "0.2.2"
tracing-log = "0.1.3"
lazy_static = "1.4.0"
ansi_term = "0.12.1"
tracing-bunyan-formatter = "0.3.2"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "rustls-tls-native-roots", "json", "gzip", "deflate"]

[dev-dependencies]
expectest = "0.12"
env_logger = "0.9"
serde = "1.0.130"
rocket = "0.5.0-rc.1"
test-log = "0.2.10"
trim-margin = "0.1.0"

[build-dependencies]
built = { version = "0.5.1", features = [ "git2" ] }
os_info = "3.0.7"
