[package]
name = "pact-protobuf-plugin"
version = "0.0.1"
edition = "2018"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>"]
description = "Pact plugin for Protobufs and gRPC"
homepage = "http://www.pactflow.io"
repository = "https://github.com/pactflow/pact-protobuf-plugin"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
tonic = "0.6.2"
prost = "0.9.0"
prost-types = "0.9.0"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
log = "0.4"
maplit = "1.0.2"
pact_matching = "0.12.1"
pact_models = "0.2.6"
pact-plugin-driver = "0.0.16"
anyhow = "1.0.42"
futures = "0.3"
async-trait = "0.1.51"
os_info = "3.0.7"
zip = "0.5.13"
serde_json = "1.0.71"
serde_yaml = "0.8.23"
tempfile = "3.2.0"
itertools = "0.10.1"
md5 = "0.7.0"
base64 = "0.13.0"
bytes = "1.1.0"
clap = "2.33.3"
log4rs = "1.0.0"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "rustls-tls-native-roots", "json", "gzip", "deflate"]

[patch.crates-io]
pact_matching = { git = 'https://github.com/pact-foundation/pact-reference' }

[dev-dependencies]
expectest = "0.12.0"
env_logger = "0.8"
pact_verifier = "0.12.3"
serde = "1.0.130"
rocket = "0.5.0-rc.1"
test-log = "0.2.8"
trim-margin = "0.1.0"

[build-dependencies]
built = { version = "0.5.1", features = [ "git2" ] }
