name: Pact-Protobuf-Plugin Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
        rust: [ stable ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Install shared mime info DB
        if: runner.os == 'macOS'
        run: brew install shared-mime-info
      - name: Tests
        run: cargo test --lib
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
      - name: Build Plugin
        run: cargo build
      - name: Clippy
        run: cargo clippy

  musl-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         docker run --rm --user "$(id -u)":"$(id -g)" -v $(pwd):/workspace -w /workspace -t pactfoundation/rust-musl-build ./scripts/musl-build.sh
