name: Release workflow

on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    env:
      pact_do_not_track: true
    steps:
      - uses: actions/checkout@v2
      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: aarch64-apple-darwin
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install LLVM
        run: choco install -y llvm
        if: runner.os == 'Windows'
      - run: ./release.sh ${{ runner.os }} ${{ github.ref }}
        shell: bash
      - name: Upload Release Assets
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release_artifacts/*
          file_glob: true
          tag: ${{ github.ref }}
